name: PR Build Check

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    name: Build Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: TypeScript Check
        run: npm run lint

      - name: Build application
        run: npm run build
        
      - name: Check build size
        run: |
          echo "📦 Build size:"
          du -sh dist
          
      - name: Success message
        run: echo "✅ Build successful!"
